version: '3.8'
services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    tty: true
    working_dir: /usr/src/app
    ports:
      - '3001:3000'
    environment:
      SSHHOST: ${IP_ADDRESS}
      SSHPORT: 22
      SSHUSER: fhdumont
      SSHAUTH: publickey
      SSHKEY: ~/.ssh/wetty
      NODE_ENV: 'development'
      BASE: /controller/p/w
    volumes:
      - ~/.ssh:/root/.ssh

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/wetty.template
      - ./auth:/usr/src/
    ports:
      - '8090:80'
    environment:
      - NGINX_DOMAIN=default_server      
      - NGINX_PORT=80
      - WETTY_HOST=wetty
      - WETTY_PORT=3000
      - CONTROLLER_PROTOCOL=http
      - CONTROLLER_URL=labs-2120nosshcontroll-if5db7py.appd-cloudmachine.com
      - CONTROLLER_PORT=8090
    command: >-
      /bin/bash -c "envsubst
      '$${NGINX_DOMAIN},$${NGINX_PORT},$${WETTY_HOST},$${WETTY_PORT},$${CONTROLLER_PROTOCOL},$${CONTROLLER_URL},$${CONTROLLER_PORT}' <
      /etc/nginx/conf.d/wetty.template > /etc/nginx/conf.d/default.conf && cat /usr/src/nginx.htpasswd > /etc/nginx/conf.d/nginx.htpasswd && nginx -g 'daemon off;'"
          
networks:
  default:
    name: nossh-proxy-base

